@baseUrl = http://localhost:8083
@connectorName = datagen

### PLUGIN LIST
GET {{baseUrl}}/connector-plugins HTTP/1.1

### CREATE CONNECTOR
PUT {{baseUrl}}/connectors/{{connectorName}}/config HTTP/1.1
Content-Type: application/json

{
    "connector.class": "io.confluent.kafka.connect.datagen.DatagenConnector",
    "kafka.topic": "transactions",
    "quickstart": "transactions",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "max.interval": 60000,
    "tasks.max": "1"
}

### Get connectors
GET {{baseUrl}}/connectors

### GET CONNECTOR STATUS
GET {{baseUrl}}/connectors/{{connectorName}}/status

### GET CONNECTOR CONFIG
GET {{baseUrl}}/connectors/{{connectorName}}/config

### Delete connector
DELETE {{baseUrl}}/connectors/{{connectorName}} HTTP/1.1

### Get log level
GET {{baseUrl}}/admin/loggers

### Set log level
PUT {{baseUrl}}/admin/loggers/root
Content-Type: application/json

{
    "level": "INFO"
}

### Set log leve
PUT {{baseUrl}}/admin/loggers/org.apache.kafka.clients.NetworkClient
Content-Type: application/json

{
    "level": "INFO"
}